# Generated by Django 6.0.2 on 2026-02-28 23:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcaFilamentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this profile", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "orca_name",
                    models.CharField(
                        default="",
                        help_text="Original profile name from OrcaSlicer JSON ('name' field)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (needs parent profile)"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Whether inheritance has been fully resolved",
                        max_length=20,
                    ),
                ),
                (
                    "inherits_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent profile name (from 'inherits' field in JSON)",
                        max_length=255,
                    ),
                ),
                ("setting_id", models.CharField(blank=True, max_length=50)),
                (
                    "instantiation",
                    models.BooleanField(
                        default=True,
                        help_text="True = selectable profile; False = base/template only",
                    ),
                ),
                (
                    "renamed_from",
                    models.CharField(
                        blank=True,
                        help_text="Old profile name before OrcaSlicer rename (used for parent lookup)",
                        max_length=255,
                    ),
                ),
                (
                    "uploaded_json",
                    models.JSONField(
                        default=dict,
                        help_text="Raw JSON content from the uploaded profile file",
                    ),
                ),
                (
                    "filament_type",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Material type(s) e.g. PLA, PETG [string[]]",
                    ),
                ),
                (
                    "filament_vendor",
                    models.JSONField(
                        blank=True, default=list, help_text="Vendor name(s) [string[]]"
                    ),
                ),
                (
                    "filament_density",
                    models.JSONField(
                        blank=True, default=list, help_text="Density in g/cm³ [float[]]"
                    ),
                ),
                (
                    "filament_diameter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Filament diameter in mm [float[]]",
                    ),
                ),
                (
                    "filament_cost",
                    models.JSONField(
                        blank=True, default=list, help_text="Price per unit [float[]]"
                    ),
                ),
                (
                    "filament_flow_ratio",
                    models.JSONField(
                        blank=True, default=list, help_text="Flow ratio [float[]]"
                    ),
                ),
                (
                    "filament_max_volumetric_speed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Max volumetric speed in mm³/s [float[]]",
                    ),
                ),
                (
                    "nozzle_temperature",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nozzle temperature per extruder in °C [int[]]",
                    ),
                ),
                (
                    "nozzle_temperature_initial_layer",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="First-layer nozzle temperature [int[]]",
                    ),
                ),
                (
                    "nozzle_temperature_range_low",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Minimum recommended nozzle temperature [int[]]",
                    ),
                ),
                (
                    "nozzle_temperature_range_high",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Maximum recommended nozzle temperature [int[]]",
                    ),
                ),
                (
                    "bed_temperature",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bed temperature per extruder in °C [int[]]",
                    ),
                ),
                (
                    "bed_temperature_initial_layer",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="First-layer bed temperature [int[]]",
                    ),
                ),
                (
                    "hot_plate_temp",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hot plate temperature [int[]]",
                    ),
                ),
                (
                    "hot_plate_temp_initial_layer",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="First-layer hot plate temperature [int[]]",
                    ),
                ),
                (
                    "cool_plate_temp",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cool plate temperature [int[]]",
                    ),
                ),
                (
                    "cool_plate_temp_initial_layer",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="First-layer cool plate temperature [int[]]",
                    ),
                ),
                (
                    "temperature_vitrification",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Softening / glass-transition temperature [int[]]",
                    ),
                ),
                (
                    "fan_min_speed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Minimum part-cooling fan speed [float[]]",
                    ),
                ),
                (
                    "fan_max_speed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Maximum part-cooling fan speed [float[]]",
                    ),
                ),
                (
                    "overhang_fan_speed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Overhang / bridge fan speed [int[]]",
                    ),
                ),
                (
                    "close_fan_the_first_x_layers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Number of initial layers with fan off [int[]]",
                    ),
                ),
                (
                    "pressure_advance",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Pressure advance / linear advance value [float[]]",
                    ),
                ),
                (
                    "enable_pressure_advance",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Enable pressure advance [bool[]]",
                    ),
                ),
                (
                    "filament_start_gcode",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Filament start G-code [string[]]",
                    ),
                ),
                (
                    "filament_end_gcode",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Filament end G-code [string[]]",
                    ),
                ),
                (
                    "filament_soluble",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Soluble material flag [bool[]]",
                    ),
                ),
                (
                    "filament_is_support",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Support material flag [bool[]]",
                    ),
                ),
                (
                    "extra_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All resolved settings not stored in dedicated columns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who imported this profile (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orca_filament_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "can_manage_orca_profiles",
                        "Can import, edit, and delete OrcaSlicer profiles",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrcaMachineProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this profile", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "orca_name",
                    models.CharField(
                        help_text="Original profile name from OrcaSlicer JSON ('name' field)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (needs parent profile)"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Whether inheritance has been fully resolved",
                        max_length=20,
                    ),
                ),
                (
                    "inherits_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent profile name (from 'inherits' field in JSON)",
                        max_length=255,
                    ),
                ),
                ("setting_id", models.CharField(blank=True, max_length=50)),
                (
                    "instantiation",
                    models.BooleanField(
                        default=True,
                        help_text="True = selectable profile; False = base/template only",
                    ),
                ),
                (
                    "renamed_from",
                    models.CharField(
                        blank=True,
                        help_text="Old profile name before OrcaSlicer rename (used for parent lookup)",
                        max_length=255,
                    ),
                ),
                (
                    "uploaded_json",
                    models.JSONField(
                        default=dict,
                        help_text="Raw JSON content from the uploaded profile file",
                    ),
                ),
                (
                    "nozzle_diameter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nozzle diameter(s) in mm, per extruder [float[]]",
                    ),
                ),
                (
                    "printable_area",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Points defining printable area [point[]]",
                    ),
                ),
                (
                    "printable_height",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum printable height in mm",
                        null=True,
                    ),
                ),
                (
                    "bed_shape",
                    models.CharField(
                        blank=True,
                        help_text="Bed shape (e.g. 'rectangular')",
                        max_length=50,
                    ),
                ),
                (
                    "extruders_count",
                    models.IntegerField(
                        blank=True, help_text="Number of extruders", null=True
                    ),
                ),
                (
                    "gcode_flavor",
                    models.CharField(
                        blank=True,
                        help_text="G-code flavor (marlin, klipper, reprapfirmware, …)",
                        max_length=50,
                    ),
                ),
                (
                    "printer_structure",
                    models.CharField(
                        blank=True,
                        help_text="Printer structure (corexy, i3, delta, …)",
                        max_length=50,
                    ),
                ),
                (
                    "printer_technology",
                    models.CharField(
                        blank=True,
                        help_text="Printer technology (FFF, SLA)",
                        max_length=10,
                    ),
                ),
                (
                    "printer_model",
                    models.CharField(
                        blank=True, help_text="Printer model/type name", max_length=255
                    ),
                ),
                (
                    "printer_variant",
                    models.CharField(
                        blank=True,
                        help_text="Printer variant (often nozzle size, e.g. '0.4')",
                        max_length=50,
                    ),
                ),
                (
                    "machine_max_speed_x",
                    models.IntegerField(
                        blank=True, help_text="Max X speed (mm/s)", null=True
                    ),
                ),
                (
                    "machine_max_speed_y",
                    models.IntegerField(
                        blank=True, help_text="Max Y speed (mm/s)", null=True
                    ),
                ),
                (
                    "machine_max_speed_z",
                    models.IntegerField(
                        blank=True, help_text="Max Z speed (mm/s)", null=True
                    ),
                ),
                (
                    "machine_max_acceleration_x",
                    models.IntegerField(
                        blank=True, help_text="Max X acceleration (mm/s²)", null=True
                    ),
                ),
                (
                    "machine_max_acceleration_y",
                    models.IntegerField(
                        blank=True, help_text="Max Y acceleration (mm/s²)", null=True
                    ),
                ),
                (
                    "machine_max_acceleration_z",
                    models.IntegerField(
                        blank=True, help_text="Max Z acceleration (mm/s²)", null=True
                    ),
                ),
                (
                    "retraction_length",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Retraction length per extruder in mm [float[]]",
                    ),
                ),
                (
                    "retraction_speed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Retraction speed per extruder in mm/s [float[]]",
                    ),
                ),
                (
                    "z_hop",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Z-hop height per extruder in mm [float[]]",
                    ),
                ),
                (
                    "machine_start_gcode",
                    models.TextField(blank=True, help_text="Start G-code template"),
                ),
                (
                    "machine_end_gcode",
                    models.TextField(blank=True, help_text="End G-code template"),
                ),
                (
                    "default_bed_type",
                    models.CharField(
                        blank=True,
                        help_text="Default bed type (e.g. 'Textured PEI Plate')",
                        max_length=100,
                    ),
                ),
                (
                    "default_filament_profile",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Default filament profile name(s) [string[]]",
                    ),
                ),
                (
                    "default_print_profile",
                    models.CharField(
                        blank=True,
                        help_text="Default process profile name",
                        max_length=255,
                    ),
                ),
                (
                    "single_extruder_multi_material",
                    models.BooleanField(
                        blank=True,
                        help_text="Single nozzle multi-material setup",
                        null=True,
                    ),
                ),
                (
                    "use_relative_e_distances",
                    models.BooleanField(
                        blank=True, help_text="Use relative E distances", null=True
                    ),
                ),
                (
                    "use_firmware_retraction",
                    models.BooleanField(
                        blank=True,
                        help_text="Use firmware retraction (G10/G11)",
                        null=True,
                    ),
                ),
                (
                    "extra_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All resolved settings not stored in dedicated columns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who imported this profile (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orca_machine_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrcaPrintPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this profile", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "orca_name",
                    models.CharField(
                        default="",
                        help_text="Original profile name from OrcaSlicer JSON ('name' field)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (needs parent profile)"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Whether inheritance has been fully resolved",
                        max_length=20,
                    ),
                ),
                (
                    "inherits_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent profile name (from 'inherits' field in JSON)",
                        max_length=255,
                    ),
                ),
                ("setting_id", models.CharField(blank=True, max_length=50)),
                (
                    "instantiation",
                    models.BooleanField(
                        default=True,
                        help_text="True = selectable profile; False = base/template only",
                    ),
                ),
                (
                    "renamed_from",
                    models.CharField(
                        blank=True,
                        help_text="Old profile name before OrcaSlicer rename (used for parent lookup)",
                        max_length=255,
                    ),
                ),
                (
                    "uploaded_json",
                    models.JSONField(
                        default=dict,
                        help_text="Raw JSON content from the uploaded profile file",
                    ),
                ),
                (
                    "layer_height",
                    models.FloatField(
                        blank=True, help_text="Layer height in mm", null=True
                    ),
                ),
                (
                    "initial_layer_print_height",
                    models.FloatField(
                        blank=True, help_text="First layer height in mm", null=True
                    ),
                ),
                (
                    "line_width",
                    models.CharField(
                        blank=True,
                        help_text="Default line width (mm or percentage e.g. '0.45' or '100%')",
                        max_length=20,
                    ),
                ),
                (
                    "outer_wall_line_width",
                    models.CharField(
                        blank=True, help_text="Outer wall line width", max_length=20
                    ),
                ),
                (
                    "inner_wall_line_width",
                    models.CharField(
                        blank=True, help_text="Inner wall line width", max_length=20
                    ),
                ),
                (
                    "initial_layer_line_width",
                    models.CharField(
                        blank=True, help_text="First layer line width", max_length=20
                    ),
                ),
                (
                    "top_surface_line_width",
                    models.CharField(
                        blank=True, help_text="Top surface line width", max_length=20
                    ),
                ),
                (
                    "sparse_infill_line_width",
                    models.CharField(
                        blank=True, help_text="Sparse infill line width", max_length=20
                    ),
                ),
                (
                    "wall_loops",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of wall loops (perimeters)",
                        null=True,
                    ),
                ),
                (
                    "top_shell_layers",
                    models.IntegerField(
                        blank=True, help_text="Number of top solid layers", null=True
                    ),
                ),
                (
                    "bottom_shell_layers",
                    models.IntegerField(
                        blank=True, help_text="Number of bottom solid layers", null=True
                    ),
                ),
                (
                    "sparse_infill_density",
                    models.CharField(
                        blank=True,
                        help_text="Infill density (percentage string e.g. '15%')",
                        max_length=20,
                    ),
                ),
                (
                    "sparse_infill_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Infill pattern (grid, gyroid, honeycomb, …)",
                        max_length=50,
                    ),
                ),
                (
                    "top_surface_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Top surface pattern (monotonic, monotonicline, …)",
                        max_length=50,
                    ),
                ),
                (
                    "outer_wall_speed",
                    models.FloatField(
                        blank=True, help_text="Outer wall speed in mm/s", null=True
                    ),
                ),
                (
                    "inner_wall_speed",
                    models.FloatField(
                        blank=True, help_text="Inner wall speed in mm/s", null=True
                    ),
                ),
                (
                    "sparse_infill_speed",
                    models.FloatField(
                        blank=True, help_text="Sparse infill speed in mm/s", null=True
                    ),
                ),
                (
                    "internal_solid_infill_speed",
                    models.FloatField(
                        blank=True,
                        help_text="Internal solid infill speed in mm/s",
                        null=True,
                    ),
                ),
                (
                    "top_surface_speed",
                    models.FloatField(
                        blank=True, help_text="Top surface speed in mm/s", null=True
                    ),
                ),
                (
                    "travel_speed",
                    models.FloatField(
                        blank=True, help_text="Travel speed in mm/s", null=True
                    ),
                ),
                (
                    "bridge_speed",
                    models.FloatField(
                        blank=True, help_text="Bridge speed in mm/s", null=True
                    ),
                ),
                (
                    "gap_infill_speed",
                    models.FloatField(
                        blank=True, help_text="Gap infill speed in mm/s", null=True
                    ),
                ),
                (
                    "initial_layer_speed",
                    models.FloatField(
                        blank=True, help_text="First layer speed in mm/s", null=True
                    ),
                ),
                (
                    "default_acceleration",
                    models.FloatField(
                        blank=True, help_text="Default acceleration in mm/s²", null=True
                    ),
                ),
                (
                    "outer_wall_acceleration",
                    models.FloatField(
                        blank=True,
                        help_text="Outer wall acceleration in mm/s²",
                        null=True,
                    ),
                ),
                (
                    "inner_wall_acceleration",
                    models.FloatField(
                        blank=True,
                        help_text="Inner wall acceleration in mm/s²",
                        null=True,
                    ),
                ),
                (
                    "travel_acceleration",
                    models.FloatField(
                        blank=True, help_text="Travel acceleration in mm/s²", null=True
                    ),
                ),
                (
                    "initial_layer_acceleration",
                    models.FloatField(
                        blank=True,
                        help_text="First layer acceleration in mm/s²",
                        null=True,
                    ),
                ),
                (
                    "enable_support",
                    models.BooleanField(
                        blank=True, help_text="Whether supports are enabled", null=True
                    ),
                ),
                (
                    "support_type",
                    models.CharField(
                        blank=True,
                        help_text="Support type (normal, tree, …)",
                        max_length=50,
                    ),
                ),
                (
                    "support_threshold_angle",
                    models.IntegerField(
                        blank=True,
                        help_text="Support threshold angle in degrees",
                        null=True,
                    ),
                ),
                (
                    "support_style",
                    models.CharField(
                        blank=True,
                        help_text="Support style (default, grid, snug, organic)",
                        max_length=50,
                    ),
                ),
                (
                    "brim_type",
                    models.CharField(
                        blank=True,
                        help_text="Brim type (no_brim, outer_only, inner_only, outer_and_inner, auto_brim)",
                        max_length=50,
                    ),
                ),
                (
                    "brim_width",
                    models.FloatField(
                        blank=True, help_text="Brim width in mm", null=True
                    ),
                ),
                (
                    "seam_position",
                    models.CharField(
                        blank=True,
                        help_text="Seam position (aligned, nearest, random, back)",
                        max_length=50,
                    ),
                ),
                (
                    "ironing_type",
                    models.CharField(
                        blank=True,
                        help_text="Ironing type (no_ironing, top_surfaces, topmost_surface, all_solid_layer)",
                        max_length=50,
                    ),
                ),
                (
                    "detect_overhang_wall",
                    models.BooleanField(
                        blank=True,
                        help_text="Enable overhang detection for walls",
                        null=True,
                    ),
                ),
                (
                    "elefant_foot_compensation",
                    models.FloatField(
                        blank=True,
                        help_text="Elephant foot compensation in mm",
                        null=True,
                    ),
                ),
                (
                    "print_sequence",
                    models.CharField(
                        blank=True,
                        help_text="Print sequence (by_layer, by_object)",
                        max_length=50,
                    ),
                ),
                (
                    "enable_prime_tower",
                    models.BooleanField(
                        blank=True,
                        help_text="Enable prime tower for multi-material",
                        null=True,
                    ),
                ),
                (
                    "filename_format",
                    models.CharField(
                        blank=True,
                        help_text="G-code filename format template",
                        max_length=255,
                    ),
                ),
                (
                    "extra_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All resolved settings not stored in dedicated columns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who imported this profile (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orca_print_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "stl_file",
                    models.FileField(blank=True, null=True, upload_to="stl_files/"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Filament color (auto-filled from Spoolman or free text)",
                        max_length=100,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Material type (auto-filled from Spoolman or free text, e.g. PLA, PETG)",
                        max_length=100,
                    ),
                ),
                (
                    "spoolman_filament_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Spoolman filament type ID — links this part to a Spoolman filament",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("filament_used_grams", models.FloatField(blank=True, null=True)),
                ("filament_used_meters", models.FloatField(blank=True, null=True)),
                ("estimated_print_time", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "print_preset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Print preset for slicing this part (inherited from project if not set)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts",
                        to="core.orcaprintpreset",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrinterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "moonraker_url",
                    models.URLField(
                        blank=True, help_text="e.g. http://192.168.1.100:7125"
                    ),
                ),
                ("moonraker_api_key", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this printer profile (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printer_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orca_machine_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="OrcaSlicer machine profile for this printer (only selectable/resolved profiles)",
                        limit_choices_to={"instantiation": True, "state": "resolved"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printers",
                        to="core.orcamachineprofile",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_manage_printers", "Can create, edit, and delete printers"),
                    (
                        "can_control_printer",
                        "Can start prints and cancel running prints",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CostProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "electricity_cost_per_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.3,
                        help_text="Electricity cost per kWh in your currency",
                        max_digits=8,
                    ),
                ),
                (
                    "printer_power_watts",
                    models.IntegerField(
                        default=200, help_text="Average power consumption in watts"
                    ),
                ),
                (
                    "printer_purchase_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Purchase price for depreciation calculation",
                        max_digits=10,
                    ),
                ),
                (
                    "printer_lifespan_hours",
                    models.IntegerField(
                        default=5000, help_text="Expected lifespan in print-hours"
                    ),
                ),
                (
                    "maintenance_cost_per_hour",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Maintenance cost per print-hour",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "printer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_profile",
                        to="core.printerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional descriptive name for this job",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("slicing", "Slicing"),
                            ("sliced", "Sliced"),
                            ("uploading", "Uploading to Printer"),
                            ("uploaded", "Uploaded"),
                            ("printing", "Printing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("filament_used_grams", models.FloatField(blank=True, null=True)),
                ("print_time_estimate", models.DurationField(blank=True, null=True)),
                (
                    "slicing_error",
                    models.TextField(
                        blank=True, help_text="Error message if slicing failed"
                    ),
                ),
                (
                    "slicing_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when slicing was started",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine profile used for slicing (determines compatible printers)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="core.orcamachineprofile",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned when the job is added to a print queue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="core.printerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintJobPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many copies of this part are in the job",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_entries",
                        to="core.part",
                    ),
                ),
                (
                    "print_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_parts",
                        to="core.printjob",
                    ),
                ),
            ],
            options={
                "unique_together": {("print_job", "part")},
            },
        ),
        migrations.AddField(
            model_name="printjob",
            name="parts",
            field=models.ManyToManyField(
                related_name="print_jobs", through="core.PrintJobPart", to="core.part"
            ),
        ),
        migrations.CreateModel(
            name="PrintJobPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Plate number within the job (1-based)"
                    ),
                ),
                (
                    "gcode_file",
                    models.FileField(blank=True, null=True, upload_to="gcode_jobs/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Preview image extracted from sliced G-code",
                        null=True,
                        upload_to="plate_thumbnails/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("printing", "Printing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("filament_used_grams", models.FloatField(blank=True, null=True)),
                ("print_time_estimate", models.DurationField(blank=True, null=True)),
                ("klipper_job_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "print_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to="core.printjob",
                    ),
                ),
            ],
            options={
                "ordering": ["plate_number"],
                "unique_together": {("print_job", "plate_number")},
            },
        ),
        migrations.CreateModel(
            name="PrintQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("printing", "Printing"),
                            ("awaiting_review", "Awaiting Review"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Urgent")],
                        default=2,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the queue (0 = next)"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this entry has been retried after failure",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum allowed retries before entry is discarded",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When printing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the printer finished (before review)",
                        null=True,
                    ),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        help_text="The specific plate (G-code) to print",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="core.printjobplate",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue",
                        to="core.printerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "position", "added_at"],
                "permissions": [
                    (
                        "can_manage_print_queue",
                        "Can add and remove jobs from the print queue",
                    ),
                    ("can_dequeue_job", "Can remove waiting jobs from the queue"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrintTimeEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_time", models.DurationField(help_text="Slicer estimate")),
                (
                    "actual_time",
                    models.DurationField(
                        blank=True, help_text="Measured actual time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_estimates",
                        to="core.part",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_estimates",
                        to="core.printerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this project (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_print_preset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default print preset used when creating new parts in this project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_projects",
                        to="core.orcaprintpreset",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_manage_projects", "Can create, edit, and delete projects")
                ],
            },
        ),
        migrations.AddField(
            model_name="part",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="core.project",
            ),
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("file", models.FileField(upload_to="file_versions/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("stl", "STL"), ("gcode", "G-code")], max_length=10
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash of the file", max_length=64
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_versions",
                        to="core.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("part", "version", "file_type")},
            },
        ),
        migrations.CreateModel(
            name="SpoolmanFilamentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spoolman_filament_id",
                    models.IntegerField(help_text="Spoolman filament type ID"),
                ),
                (
                    "spoolman_filament_name",
                    models.CharField(
                        blank=True,
                        help_text="Cached display name from Spoolman (automatically updated)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this mapping (informational only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spoolman_filament_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orca_filament_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="OrcaSlicer filament profile to use when slicing with this filament type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spoolman_mappings",
                        to="core.orcafilamentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["spoolman_filament_name", "spoolman_filament_id"],
                "permissions": [
                    (
                        "can_manage_filament_mappings",
                        "Can create, edit, and delete filament mappings",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("spoolman_filament_id",),
                        name="unique_spoolman_filament_mapping",
                    )
                ],
            },
        ),
    ]
