# Generated by Django 6.0.2 on 2026-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_role_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcafilamentprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='orcamachineprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='orcaprintpreset',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, help_text='Optional — derived from the uploaded filename if left empty.', max_length=255),
        ),
        migrations.AlterField(
            model_name='printerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown formatting.'),
        ),
    ]
