# Generated by Django 6.0.3 on 2026-03-03 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orcafilamentprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent project — set to make this a sub-project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='core.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many times this sub-project is needed within its parent project.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
