# Generated by Django 6.0.3 on 2026-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_parent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='estimation_error',
            field=models.TextField(blank=True, default='', help_text='Error message from the last failed estimation attempt.'),
        ),
        migrations.AddField(
            model_name='part',
            name='estimation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='none', help_text='Status of the background filament/time estimation.', max_length=10),
        ),
    ]
