# Generated by Django 6.0.3 on 2026-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_part_estimation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='estimation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('estimating', 'Estimating'), ('success', 'Success'), ('error', 'Error')], default='none', help_text='Status of the background filament/time estimation.', max_length=10),
        ),
    ]
