# Generated by Django 6.0.3 on 2026-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_part_estimation_estimating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoolmanfilamentmapping',
            name='spoolman_color_hex',
            field=models.CharField(blank=True, help_text='Cached hex color from Spoolman (e.g. FF0000), automatically updated', max_length=7),
        ),
    ]
