# Generated by Django 6.0.3 on 2026-03-15 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_spoolmanfilamentmapping_spoolman_color_hex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwarePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('screws', 'Screws'), ('nuts', 'Nuts'), ('bolts', 'Bolts'), ('threaded_inserts', 'Threaded Inserts'), ('springs', 'Springs'), ('bearings', 'Bearings'), ('motors', 'Motors'), ('electronics', 'Electronics'), ('magnets', 'Magnets'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Link to a webshop or datasheet.')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Project-specific notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='core.hardwarepart')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_assignments', to='core.project')),
            ],
            options={
                'ordering': ['hardware_part__category', 'hardware_part__name'],
                'unique_together': {('project', 'hardware_part')},
            },
        ),
    ]
