# Generated by Django 6.0.3 on 2026-03-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_projectdocument_hardwarepart_projecthardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
