# Generated by Django 6.0.3 on 2026-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_allow_blank_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image shown in the project list and detail views.', null=True, upload_to='project_images/'),
        ),
    ]
