"""Remove individual settings fields and extra_settings from OrcaSlicer profile models.

All settings are now stored in the single ``settings`` JSONField.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_migrate_settings_data"),
    ]

    operations = [
        # ── OrcaFilamentProfile ─────────────────────────────────────────
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_type"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_vendor"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_density"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_diameter"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_cost"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_flow_ratio"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_max_volumetric_speed"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="nozzle_temperature"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="nozzle_temperature_initial_layer"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="nozzle_temperature_range_low"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="nozzle_temperature_range_high"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="bed_temperature"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="bed_temperature_initial_layer"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="hot_plate_temp"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="hot_plate_temp_initial_layer"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="cool_plate_temp"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="cool_plate_temp_initial_layer"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="temperature_vitrification"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="fan_min_speed"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="fan_max_speed"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="overhang_fan_speed"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="close_fan_the_first_x_layers"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="pressure_advance"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="enable_pressure_advance"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_start_gcode"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_end_gcode"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_soluble"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="filament_is_support"),
        migrations.RemoveField(model_name="orcafilamentprofile", name="extra_settings"),
        # ── OrcaPrintPreset ─────────────────────────────────────────────
        migrations.RemoveField(model_name="orcaprintpreset", name="layer_height"),
        migrations.RemoveField(model_name="orcaprintpreset", name="initial_layer_print_height"),
        migrations.RemoveField(model_name="orcaprintpreset", name="line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="outer_wall_line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="inner_wall_line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="initial_layer_line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="top_surface_line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="sparse_infill_line_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="wall_loops"),
        migrations.RemoveField(model_name="orcaprintpreset", name="top_shell_layers"),
        migrations.RemoveField(model_name="orcaprintpreset", name="bottom_shell_layers"),
        migrations.RemoveField(model_name="orcaprintpreset", name="sparse_infill_density"),
        migrations.RemoveField(model_name="orcaprintpreset", name="sparse_infill_pattern"),
        migrations.RemoveField(model_name="orcaprintpreset", name="top_surface_pattern"),
        migrations.RemoveField(model_name="orcaprintpreset", name="outer_wall_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="inner_wall_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="sparse_infill_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="internal_solid_infill_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="top_surface_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="travel_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="bridge_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="gap_infill_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="initial_layer_speed"),
        migrations.RemoveField(model_name="orcaprintpreset", name="default_acceleration"),
        migrations.RemoveField(model_name="orcaprintpreset", name="outer_wall_acceleration"),
        migrations.RemoveField(model_name="orcaprintpreset", name="inner_wall_acceleration"),
        migrations.RemoveField(model_name="orcaprintpreset", name="travel_acceleration"),
        migrations.RemoveField(model_name="orcaprintpreset", name="initial_layer_acceleration"),
        migrations.RemoveField(model_name="orcaprintpreset", name="enable_support"),
        migrations.RemoveField(model_name="orcaprintpreset", name="support_type"),
        migrations.RemoveField(model_name="orcaprintpreset", name="support_threshold_angle"),
        migrations.RemoveField(model_name="orcaprintpreset", name="support_style"),
        migrations.RemoveField(model_name="orcaprintpreset", name="brim_type"),
        migrations.RemoveField(model_name="orcaprintpreset", name="brim_width"),
        migrations.RemoveField(model_name="orcaprintpreset", name="seam_position"),
        migrations.RemoveField(model_name="orcaprintpreset", name="ironing_type"),
        migrations.RemoveField(model_name="orcaprintpreset", name="detect_overhang_wall"),
        migrations.RemoveField(model_name="orcaprintpreset", name="elefant_foot_compensation"),
        migrations.RemoveField(model_name="orcaprintpreset", name="print_sequence"),
        migrations.RemoveField(model_name="orcaprintpreset", name="enable_prime_tower"),
        migrations.RemoveField(model_name="orcaprintpreset", name="filename_format"),
        migrations.RemoveField(model_name="orcaprintpreset", name="extra_settings"),
        # ── OrcaMachineProfile ──────────────────────────────────────────
        migrations.RemoveField(model_name="orcamachineprofile", name="nozzle_diameter"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printable_area"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printable_height"),
        migrations.RemoveField(model_name="orcamachineprofile", name="bed_shape"),
        migrations.RemoveField(model_name="orcamachineprofile", name="extruders_count"),
        migrations.RemoveField(model_name="orcamachineprofile", name="gcode_flavor"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printer_structure"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printer_technology"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printer_model"),
        migrations.RemoveField(model_name="orcamachineprofile", name="printer_variant"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_speed_x"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_speed_y"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_speed_z"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_acceleration_x"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_acceleration_y"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_max_acceleration_z"),
        migrations.RemoveField(model_name="orcamachineprofile", name="retraction_length"),
        migrations.RemoveField(model_name="orcamachineprofile", name="retraction_speed"),
        migrations.RemoveField(model_name="orcamachineprofile", name="z_hop"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_start_gcode"),
        migrations.RemoveField(model_name="orcamachineprofile", name="machine_end_gcode"),
        migrations.RemoveField(model_name="orcamachineprofile", name="default_bed_type"),
        migrations.RemoveField(model_name="orcamachineprofile", name="default_filament_profile"),
        migrations.RemoveField(model_name="orcamachineprofile", name="default_print_profile"),
        migrations.RemoveField(model_name="orcamachineprofile", name="single_extruder_multi_material"),
        migrations.RemoveField(model_name="orcamachineprofile", name="use_relative_e_distances"),
        migrations.RemoveField(model_name="orcamachineprofile", name="use_firmware_retraction"),
        migrations.RemoveField(model_name="orcamachineprofile", name="extra_settings"),
    ]
