# Generated by Django 6.0.3 on 2026-03-31 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_individual_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamachineprofile',
            name='orca_name',
            field=models.CharField(default='', help_text="Original profile name from OrcaSlicer JSON ('name' field)", max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='estimation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('estimating', 'Estimating'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='none', help_text='Status of the background filament/time estimation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('slicing', 'Slicing'), ('sliced', 'Sliced'), ('uploading', 'Uploading to Printer'), ('uploaded', 'Uploaded'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='printjobplate',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('printing', 'Printing'), ('awaiting_review', 'Awaiting Review')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent project — set to make this a sub-project.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subprojects', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='orcafilamentprofile',
            index=models.Index(fields=['state', 'instantiation'], name='orcafilamentprofile_st_ins_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamachineprofile',
            index=models.Index(fields=['state', 'instantiation'], name='orcamachineprofile_st_ins_idx'),
        ),
        migrations.AddIndex(
            model_name='orcaprintpreset',
            index=models.Index(fields=['state', 'instantiation'], name='orcaprintpreset_st_ins_idx'),
        ),
        migrations.AddIndex(
            model_name='printqueue',
            index=models.Index(fields=['status', 'printer'], name='printqueue_status_printer_idx'),
        ),
        migrations.AddConstraint(
            model_name='costprofile',
            constraint=models.CheckConstraint(condition=models.Q(('printer_lifespan_hours__gt', 0)), name='costprofile_lifespan_hours_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='part_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='printjobplate',
            constraint=models.CheckConstraint(condition=models.Q(('plate_number__gte', 1)), name='printjobplate_plate_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='printqueue',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 4)), name='printqueue_priority_between_1_and_4'),
        ),
        migrations.AddConstraint(
            model_name='printqueue',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='printqueue_position_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='printqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('plate',), name='printqueue_unique_plate_when_waiting'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='project_quantity_gte_1'),
        ),
    ]
