# Generated by Django 6.0.3 on 2026-03-27 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_individual_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='printjobplate',
            old_name='klipper_job_id',
            new_name='remote_job_id',
        ),
        migrations.AlterField(
            model_name='printjobplate',
            name='remote_job_id',
            field=models.CharField(blank=True, help_text='Filename or job ID on the remote printer after upload', max_length=255),
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='bambu_device_id',
            field=models.CharField(blank=True, help_text='Device serial number from Bambu Lab Cloud', max_length=255),
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='bambu_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Local IP address for direct LAN communication (FTP upload)', null=True),
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='printer_type',
            field=models.CharField(choices=[('klipper', 'Klipper/Moonraker'), ('bambulab', 'Bambu Lab')], default='klipper', help_text='Determines which communication backend is used', max_length=20),
        ),
        migrations.CreateModel(
            name='BambuCloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Bambu Lab account email address', max_length=254)),
                ('region', models.CharField(choices=[('global', 'Global'), ('china', 'China')], default='global', max_length=10)),
                ('token', models.TextField(blank=True, help_text='JWT access token (stored encrypted)')),
                ('bambu_uid', models.CharField(blank=True, help_text='Bambu Lab user ID (required for MQTT connections)', max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the current JWT token expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently usable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bambu_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='bambu_account',
            field=models.ForeignKey(blank=True, help_text='Bambu Lab Cloud account for authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='core.bambucloudaccount'),
        ),
    ]
