# Generated by Django 6.0.3 on 2026-04-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_remote_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printqueue',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='Last error reported by the printer backend (if any)'),
        ),
        migrations.AddField(
            model_name='printqueue',
            name='progress',
            field=models.FloatField(blank=True, help_text='Live print progress 0..1 from the printer backend', null=True),
        ),
        migrations.AddField(
            model_name='printqueue',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time the status was updated from the printer backend', null=True),
        ),
    ]
