# Generated by Django 6.1.1 on 2026-09-18 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_printqueue_progress_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprofile',
            name='electricity_cost_per_kwh',
            field=models.DecimalField(decimal_places=4, default=0.3, help_text='Electricity cost per kWh in your currency', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='costprofile',
            name='maintenance_cost_per_hour',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Maintenance cost per print-hour', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='costprofile',
            name='printer_lifespan_hours',
            field=models.IntegerField(default=5000, help_text='Expected lifespan in print-hours', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='costprofile',
            name='printer_power_watts',
            field=models.IntegerField(default=200, help_text='Average power consumption in watts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='costprofile',
            name='printer_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchase price for depreciation calculation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='costprofile',
            constraint=models.CheckConstraint(condition=models.Q(('printer_power_watts__gte', 0)), name='costprofile_power_watts_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='costprofile',
            constraint=models.CheckConstraint(condition=models.Q(('printer_purchase_cost__gte', 0)), name='costprofile_purchase_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='costprofile',
            constraint=models.CheckConstraint(condition=models.Q(('electricity_cost_per_kwh__gte', 0)), name='costprofile_electricity_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='costprofile',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_cost_per_hour__gte', 0)), name='costprofile_maintenance_cost_gte_0'),
        ),
    ]
