# Generated by Django 6.1.1 on 2026-09-20 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_model_constraints_and_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this child module the assembly needs.', validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering of this child within the assembly.')),
                ('child_project', models.ForeignKey(help_text='The module included in the parent assembly.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.project')),
                ('parent_project', models.ForeignKey(help_text='The assembly that contains the child module.', on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='core.project')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('parent_project', 'child_project'), name='uniq_projectcomponent_parent_child'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='projectcomponent_quantity_gte_1'), models.CheckConstraint(condition=models.Q(('parent_project', models.F('child_project')), _negated=True), name='projectcomponent_no_self_parent')],
            },
        ),
        migrations.CreateModel(
            name='ProjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this part the module needs.', validators=[django.core.validators.MinValueValidator(1)])),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering of this part within the module.')),
                ('part', models.ForeignKey(help_text='The reusable part referenced by the module/assembly.', on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.part')),
                ('project', models.ForeignKey(help_text='The module/assembly this part is included in.', on_delete=django.db.models.deletion.CASCADE, related_name='part_links', to='core.project')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('project', 'part'), name='uniq_projectpart_project_part'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='projectpart_quantity_gte_1')],
            },
        ),
    ]
