# Generated by Django 6.1.1 on 2026-09-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_composition_edges'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjobpart',
            name='target_assembly',
            field=models.ForeignKey(blank=True, help_text='Top-level assembly this print contributes to (for per-variant progress). Null = unattributed (counted only in global progress).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_job_parts', to='core.project'),
        ),
    ]
