# Generated by Django 6.0.3 on 2026-09-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_printjobpart_target_assembly'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='part',
            name='part_quantity_gte_1',
        ),
        migrations.RemoveField(
            model_name='part',
            name='project',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
    ]
