# Generated by Django 6.1.1 on 2026-09-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_part_project_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthardware',
            name='hardware_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='core.hardwarepart'),
        ),
    ]
