# Generated by Django 6.1.1 on 2026-09-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_hardware_part_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='print_preset',
            field=models.ForeignKey(blank=True, help_text='Print preset resolved for this job at creation (one preset per job).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='core.orcaprintpreset'),
        ),
    ]
