# Generated by Django 6.1.1 on 2026-09-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_printjob_print_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='estimated_with_preset',
            field=models.ForeignKey(blank=True, help_text='The print preset that produced the currently stored estimate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_parts', to='core.orcaprintpreset'),
        ),
    ]
