# Generated by Django 6.1.1 on 2026-09-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_part_estimated_with_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='estimation_requested_preset',
            field=models.ForeignKey(blank=True, help_text='Transient queue-time channel: a whole-project re-estimate pins the project-context preset here so the worker estimates with it. Consumed (cleared) by the worker on claim; never used as estimate provenance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_requests', to='core.orcaprintpreset'),
        ),
    ]
