"""
Django settings for layernexus project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set the DJANGO_SECRET_KEY environment variable.
_secret_key = os.environ.get("DJANGO_SECRET_KEY", "")
if not _secret_key:
    if DEBUG:
        _secret_key = "django-insecure-dev-only-key-not-for-production"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY environment variable is required when DEBUG is off.")
SECRET_KEY = _secret_key

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = (
    os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if os.environ.get("CSRF_TRUSTED_ORIGINS") else []
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "core",
]

# Django REST Framework — token-authenticated build API under /api/v1/.
# Per-user tokens carry the existing RBAC (writes require core.can_manage_projects,
# reads require authentication). Session auth is kept so the browsable API works
# for a logged-in staff user.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_THROTTLE_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "layernexus.settings.SecurityHeadersMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "layernexus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.app_name",
                "core.context_processors.app_version",
                "core.context_processors.allow_registration",
            ],
        },
    },
]

WSGI_APPLICATION = "layernexus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DATABASE_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# User registration (set to False to disable self-registration)
ALLOW_REGISTRATION = os.environ.get("ALLOW_REGISTRATION", "true").lower() in (
    "true",
    "1",
    "yes",
)

# Application name
APP_NAME = "LayerNexus"

# Application version (read from VERSION file, overridable via env/Docker ARG)
_version_file = BASE_DIR / "VERSION"
APP_VERSION = os.environ.get(
    "APP_VERSION",
    _version_file.read_text().strip() if _version_file.exists() else "dev",
)

SPECTACULAR_SETTINGS = {
    "TITLE": "LayerNexus API",
    "DESCRIPTION": (
        "Token-authenticated REST API for building LayerNexus projects iteratively. "
        "Covers projects, sub-project composition edges, parts (incl. STL/3MF upload), "
        "documents, and hardware. Printing (print jobs, queue, printers) is out of scope. "
        "BREAKING since Phase 6: Part has no project/quantity fields — "
        "attach parts to projects via POST /api/v1/projects/{id}/parts/."
    ),
    "VERSION": APP_VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "core": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# OrcaSlicer API
# URL of the orca-slicer-api service (https://github.com/AFKFelix/orca-slicer-api)
ORCASLICER_API_URL = os.environ.get("ORCASLICER_API_URL", "http://localhost:3000")

# Spoolman
# URL of the Spoolman instance for filament tracking (https://github.com/Donkie/Spoolman)
SPOOLMAN_URL = os.environ.get("SPOOLMAN_URL", "")

# Security settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_HTTPONLY = True
# 14-day default; sliding window when SESSION_SAVE_EVERY_REQUEST is on.
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", "1209600"))
SESSION_SAVE_EVERY_REQUEST = os.environ.get("SESSION_SAVE_EVERY_REQUEST", "1") == "1"
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Baseline Content-Security-Policy (defense in depth).
#
# This is a *conservative* policy: it still permits ``'unsafe-inline'`` and
# ``'unsafe-eval'`` because the UI relies on inline event handlers, inline
# ``<script type="importmap">`` / ES-module blocks, inline styles, Bootstrap
# and three.js (loaded from jsDelivr).  A stricter nonce-based policy would
# require reworking every template and is intentionally out of scope here.
#
# The concrete wins over "no CSP" are: locking active content to our own
# origin plus jsDelivr, forbidding plugins/objects, pinning the document
# base URI, forbidding framing (clickjacking), and restricting form targets.
# Uploaded media is served under a much stricter per-response CSP
# (see ``layernexus.urls.MEDIA_CSP``), which this middleware must not weaken.
BASELINE_CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; "
    "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
    "img-src 'self' data: blob:; "
    "font-src 'self' https://cdn.jsdelivr.net; "
    "connect-src 'self'; "
    "worker-src 'self' blob:; "
    "frame-ancestors 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "object-src 'none'"
)


class SecurityHeadersMiddleware:
    """Attach the baseline CSP to responses that do not already set one.

    ``HttpResponseBase.setdefault`` is used so responses that intentionally
    declare a stricter policy (e.g. the sandboxed media responses) keep it.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        response.setdefault("Content-Security-Policy", BASELINE_CSP)
        return response
